name: "3005hacks"
baseurl: /3005hacks

ftp_host: '3005hacks.com'
ftp_dir: '/var/www/nyctender.com/public_html'
ftp_passive: false

# optional
ftp_port: 22
ftp_username: 'root'
ftp_password: 'ayylmao101'